version: '3.8'
services:
    redis:
        image: redis:7
        ports:
            - "6379:6379"
        env_file:
            - .env.example
        healthcheck:
            test: ["CMD","redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        container_name: marketflow
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
          - ./.env.example   
        depends_on:
            db:
                condition: service_healthy          
        volumes:
          - ./config:/app/config:ro   
          - ./logs:/app/logs
        ports:
          - "8080:8080"               
        depends_on:
          - redis
          - db
          - exchange1
          - exchange2
          - exchange3


    db:
        image: postgres:15
        container_name: postgres
        env_file:
            - .env.example
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: leetdb
        ports:
            - "5433:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/db/init.sql

    exchange1:
        image: exchange1
        container_name: exchange1
        ports:
            - "40101:40101"

    exchange2:
        image: exchange2
        container_name: exchange2
        ports:
            - "40102:40102"

    exchange3:
        image: exchange3
        container_name: exchange3
        ports:
            - "40103:40103"